### ISSUE TITLE
Annoying degree of freedom question

### ISSUE THREAD

**Issue by jecowan** [brbackes/vamR#10]
Does this do the DoF correctly for models with absorbed variables? Don't you want to count the number of FE?

https://github.com/brbackes/vamR/blob/58606cc30454b6633df03ac21399f5a610db23e6/R/vam_ado.R#L203C1-L204C1

**Comment by jecowan** [comment]
Ah, sorry, I misunderstood how fixest works!

**Comment by brbackes** [comment]
You must be really deep in the guts of fixest/areg to be noticing dof adjustments!
